### PR TITLE
actually create EPHEMERAL nodes

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by robert-chiniquy** [comment]
Wait what was this doing before?

**Comment by rphillips** [comment]
the argument was for the 'acl', so it was creating regular nodes.

**Comment by robert-chiniquy** [comment]
Docs specify that parameter as optional: https://www.npmjs.com/package/node-zookeeper-client#void-create-path-data-acls-mode-callback

**Comment by rphillips** [comment]
Hmm. Perhaps it is doing the right thing.

**Comment by robert-chiniquy** [comment]
https://github.com/alexguan/node-zookeeper-client/blob/master/index.js#L357

^ looks like the method has all the typical JS optional argument complexity.

If the nodes weren't ephemeral, I think the locking algo would never have worked. You can also use the `bin/ephemerals` and `bin/non-ephemerals` script to look at your ZK state to validate the node types.

**Comment by rphillips** [comment]
Yep. You are right. Thanks robert.

**Pull request closed without merging**
